# Generated by Django 5.2.4 on 2025-07-12 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='query_log',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='knowledge_b_event_t_377c0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='knowledge_b_user_id_ef8984_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmetrics',
            name='knowledge_b_metric__dad866_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='persona_used',
            field=models.CharField(default='helpful_tutor', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='metric_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='textbookcontent',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
