# Generated by Django 5.2.4 on 2025-07-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_alter_userfeedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='rating_comment',
            field=models.TextField(blank=True),
        ),
    ]
